version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    ports: 
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://elasticsearch:9200"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  esdata:
    driver: local